---
- name: Get query pack from S3
  aws_s3:
    bucket: opensoc-kolide-query-packs
    object: "{{ item }}.json"
    dest: "roles/query-packs/files/{{ item }}.json"
    mode: get

- name: Login and get bearer token
  uri:
    url: "{{ kolide_url }}/api/v1/kolide/login"
    method: POST
    body: "{\"password\":\"{{ kolide_pw }}\",\"username\":\"{{ kolide_user }}\"}"
    body_format: json
    headers:
      Content-Type: application/json
      DNT: 1
    validate_certs: no
    return_content: yes
  register: response

- name: Get token
  set_fact:
    bearer_token: "{{ response['json']['token'] }}"

- name: Create query pack
  shell: "{{ lookup('template', 'create-queries.py.j2') }}"
  args:
    chdir: "{{ role_path }}/files"
    executable: /usr/local/bin/python
  register: save_query_result
  ignore_errors: True
